name: Run Jest Tests and Commit Reports

on:
  push:
    branches: [ main ]

jobs:
  test_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is crucial for committing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Save JSON Report
        run: |
          mkdir -p test-reports
          TIMESTAMP=$(date +%s)
          npx jest --json --outputFile=test-reports/jest-report-$TIMESTAMP.json

      - name: Commit Jest Report to Repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add test-reports/*.json
          git commit -m "Add Jest test report from GitHub Actions" || true
          git push