name: Run Jest Tests, Commit Reports, and Send File Tree

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test_and_commit_and_send:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Get changed files
        id: files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $CHANGED_FILES"

      - name: Send Changed Files to Server
        run: |
          echo "Preparing to send changed files..."
          for file in $CHANGED_FILES; do
            echo "Processing file: $file"
            FILE_CONTENT=$(cat "$file" | jq -Rs .)
            echo "File content length: $(echo $FILE_CONTENT | wc -c)"
            curl -v -X POST ${{ secrets.SERVER_URL }}/inputCode \
              -H "Content-Type: application/json" \
              -d "{\"file_path\":\"$file\",\"content\":$FILE_CONTENT,\"commit_sha\":\"${GITHUB_SHA}\"}"
          done

      - name: Run Jest Tests and Generate Report
        run: |
          echo "Running Jest tests..."
          npx jest --json --outputFile=jest-report.json || true
          cat jest-report.json

      - name: Commit Test Report
        run: |
          echo "Saving jest report..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add jest-report.json
          git commit -m "Add Jest test report for ${{ github.sha }}" || echo "No changes to commit"
          git push
