name: Send Files to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  send_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
          echo "Changed files: $CHANGED_FILES"

      - name: Send changed files to server
        run: |
          for file in $CHANGED_FILES; do
            echo "---- Sending $file ----"
            CONTENT=$(jq -Rs . < "$file")   # escape file content safely
            RESPONSE=$(curl -s -X POST https://5021a42acf18.ngrok-free.app/inputCode \
              -H "Content-Type: application/json" \
              -d "{\"file_path\":\"$file\",\"content\":$CONTENT}")
            echo "✅ Server response for $file:"
            echo "$RESPONSE"
            echo "------------------------"
          done
