name: Run Jest Tests, Commit Reports, and Send File Tree

on:
  push:
    branches: [ main ]

jobs:
  test_and_commit_and_send:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests and Save JSON Report
        run: |
          mkdir -p test-reports
          TIMESTAMP=$(date +%s)
          npx jest --json --outputFile=test-reports/jest-report-$TIMESTAMP.json

      - name: Commit Jest Report to Repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add test-reports/*.json
          git commit -m "Add Jest test report from GitHub Actions" || true
          git push

      - name: Generate File Tree JSON
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            function getFilesWithContent(dir = __dirname, baseDir = dir) {
              const output = {};
              const includeExt = new Set(['.js', '.ts', '.jsx', '.tsx']);
              function walk(d) {
                for (const f of fs.readdirSync(d)) {
                  if (f === 'node_modules' || f === 'ensure-jest.js' || f === 'file-tree-parser.js') continue;
                  const full = path.join(d, f);
                  const stat = fs.statSync(full);
                  if (stat.isDirectory()) walk(full);
                  else if (includeExt.has(path.extname(f).toLowerCase())) {
                    const rel = path.relative(baseDir, full).replace(/\\\\/g, '/');
                    output[rel] = fs.readFileSync(full, 'utf-8');
                  }
                }
              }
              walk(dir);
              return output;
            }
            const tree = getFilesWithContent();
            fs.writeFileSync('file-tree.json', JSON.stringify(tree));
          "


      - name: Send File Tree to Server
        run: |
          curl -X POST https://133c5861a54a.ngrok-free.app/receive \
            -H "Content-Type: application/json" \
            --data-binary @file-tree.json
